In [54]:
import pandas as pd
import numpy as np
import sklearn as sk
from sklearn.preprocessing import LabelEncoder
%matplotlib inline
DATAPATH = 'mushrooms.csv'

data = pd.read_csv(DATAPATH, sep=';')
#data.shape #nubber of strings and columns
data.head(5)
for col in data.columns: #number of zero cells
    print("{} : {}".format(col, data[col].isnull().sum()))

le = LabelEncoder() #1 poisonous 0 edible
data['class'] = le.fit_transform(data['class'])
data.head()

encoded_data = pd.get_dummies(data)
encoded_data.head(5)

from sklearn.model_selection import train_test_split
y = data['class'].values.reshape(-1, 1)
X = encoded_data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

class : 0
cap-shape : 0
cap-surface : 0
cap-color : 0
bruises : 0
odor : 0
gill-attachment : 0
gill-spacing : 0
gill-size : 0
gill-color : 0
stalk-shape : 0
stalk-root : 0
stalk-surface-above-ring : 0
stalk-surface-below-ring : 0
stalk-color-above-ring : 0
stalk-color-below-ring : 0
veil-type : 0
veil-color : 0
ring-number : 0
ring-type : 0
spore-print-color : 0
population : 0
habitat : 0


In [55]:
from sklearn.svm import SVC
svclassifier = SVC()
svclassifier.fit(X_train, y_train)

/opt/python/envs/default/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC()

In [56]:
from sklearn.model_selection import cross_val_score
cross_val_score(svclassifier, X, y, cv=5, n_jobs=-1)

array([1.        , 1.        , 1.        , 1.        , 0.99751861])

In [57]:
from sklearn.neighbors import KNeighborsClassifier
knclassifier = KNeighborsClassifier()
cross_val_score(knclassifier, X, y, cv=5, n_jobs=-1)

array([1.        , 1.        , 1.        , 1.        , 0.99751861])

In [58]:
from sklearn.model_selection import GridSearchCV

parameters = {
      "n_neighbors": [3, 5, 10, 15, 20],
      "weights" : ['uniform', 'distance'],
      "p" : [1, 2,3,4]
}

neighbors_model = KNeighborsClassifier()
clf = GridSearchCV(neighbors_model, parameters)
clf.fit(X, y)

clf.best_params_

/opt/python/envs/default/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/opt/python/envs/default/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/opt/python/envs/default/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/opt/python/envs/default/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected

{'n_neighbors': 3, 'p': 1, 'weights': 'uniform'}

In [59]:
knclassifier = KNeighborsClassifier(n_neighbors= 3, p= 1, weights= 'uniform')
knclassifier.fit(X_train, y_train)
cross_val_score(knclassifier, X, y, cv=5, n_jobs=-1)

/opt/python/envs/default/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


array([1.        , 1.        , 1.        , 1.        , 0.99751861])

In [60]:
y_pred_svc = svclassifier.predict(X_test) #prognosis
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred_svc))
print(classification_report(y_test,y_pred_svc))
svclassifier.fit(X_test, y_test)
svclassifier.score(X_test, y_test)

[[362   0]
 [  1  41]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       362
           1       1.00      0.98      0.99        42

    accuracy                           1.00       404
   macro avg       1.00      0.99      0.99       404
weighted avg       1.00      1.00      1.00       404



/opt/python/envs/default/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


1.0

In [61]:
y_pred_kn = knclassifier.predict(X_test) #prognosis
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred_kn))
print(classification_report(y_test,y_pred_kn))
svclassifier.fit(X_test, y_test)
svclassifier.score(X_test, y_test)

[[362   0]
 [  1  41]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       362
           1       1.00      0.98      0.99        42

    accuracy                           1.00       404
   macro avg       1.00      0.99      0.99       404
weighted avg       1.00      1.00      1.00       404



/opt/python/envs/default/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


1.0