In [4]:
import numpy
import ga

"""
The y=target is to maximize this equation ASAP:
    y = w1x1+w2x2+w3x3+w4x4+w5x5+6wx6
    where (x1,x2,x3,x4,x5,x6)=(5,-1,6.5,7,-13,-5.3)
    best values for the 6 weights w1 to w6?
"""

equation_inputs = [5,-1,6.5,7,-13,-5.3]

# Number of the weights
num_weights = 6

sol_per_pop = 8
num_parents_mating = 4

# Defining the population size.
pop_size = (sol_per_pop,num_weights) # The population will have sol_per_pop chromosome where each chromosome has num_weights genes.
#initial population.
new_population = numpy.random.uniform(low=-4.0, high=4.0, size=pop_size)
print(new_population)

num_generations = 5
for generation in range(num_generations):
    #the fitness of each chromosome
    fitness = ga.cal_pop_fitness(equation_inputs, new_population)

    #the best parents
    parents = ga.select_mating_pool(new_population, fitness, 
                                      num_parents_mating)

    #next generation
    offspring_crossover = ga.crossover(parents,
                                       offspring_size=(pop_size[0]-parents.shape[0], num_weights))

    #variations
    offspring_mutation = ga.mutation(offspring_crossover)

    #the new population based on the parents and offspring.
    new_population[0:parents.shape[0], :] = parents
    new_population[parents.shape[0]:, :] = offspring_mutation

    print("Generation : ", generation)
    # The best result in the current iteration.
    print("Best result : ", numpy.max(numpy.sum(new_population*equation_inputs, axis=1)))

# Getting the best solution after iterating finishing all generations.
#At first, the fitness is calculated for each solution in the final generation.
fitness = ga.cal_pop_fitness(equation_inputs, new_population)
# Then return the index of that solution corresponding to the best fitness.
best_match_idx = numpy.where(fitness == numpy.max(fitness))

print("Best solution :\n ", new_population[best_match_idx, :])
print("Best solution fitness : ", fitness[best_match_idx])

[[-2.88990074  0.20653899  2.1446852  -3.64889441  0.78643183  2.08221196]
 [-1.67471524  2.1540324   3.87381219  3.27553933 -0.62401266 -0.46630311]
 [ 3.06802627 -1.99423642 -2.67591203  0.4283014  -3.1146057  -2.50240049]
 [-3.74590407  3.06653056  2.11530595 -0.59416426  3.91129418 -1.94616184]
 [ 0.8875195   3.22821466  3.83900024  2.04927872 -0.18217826  0.87761676]
 [ 2.43680845  2.33313684 -3.91499296  0.4749967  -1.46660671  1.76166967]
 [ 1.49362811 -0.67930479 -1.35267208 -1.09333231 -0.1595174  -3.55746642]
 [ 1.69800063  2.78300626  0.79371612 -3.77111029 -3.67267603 -0.75800064]]
Generation :  0
Best result :  65.86018303390912
Generation :  1
Best result :  94.13688725933756
Generation :  2
Best result :  98.32721517423431
Generation :  3
Best result :  98.32721517423431
Generation :  4
Best result :  109.40942780274287
Best solution :
  [[[ 0.8875195   3.22821466  3.83900024  0.4283014  -5.152747
   -2.50240049]]]
Best solution fitness :  [109.4094278]
